fix: add missing includes
# Fix

When building with the `make` instructions in the
readme on ubuntu 24.04, you get the following
compiler error:

```
file.h:49:9: note: 'uint32_t' is defined in header
'<cstdint>'; did you forget to '#include <cstdint>'?
```

Note that this commit does actually make building
on ubuntu 24.04 work, as you get this error
instead:

```
gfx/bitmap.cpp:13:10: fatal error:
stb_image_resize2.h: No such file or directory
```